package com.ledger.app.data.db

import androidx.room.AutoMigration
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(
    entities = [
        TransactionEntity::class, RuleEntity::class, SenderEntity::class,
        CategoryEntity::class, OwnAccountEntity::class, OwnAccountNameEntity::class,
    ],
    version = 6,
    exportSchema = true,
    // Add-only migrations are generated by Room and (thanks to exportSchema)
    // validated at compile time:
    //   v1 -> v2  adds the `categories` table
    //   v2 -> v3  adds the `own_accounts` table and `transactions.selfTransfer`
    //             (NOT NULL DEFAULT 0 — existing rows start as normal spending
    //             and are re-evaluated once the user names their own accounts).
    //   v3 -> v4  adds the `own_account_names` table, `own_accounts.institution`,
    //             and `transactions.referenceKeys` (both nullable; existing rows
    //             are backfilled on first use — see refreshSelfTransfers).
    // v4 -> v5 adds a column *and* moves data, so it is hand-written below.
    autoMigrations = [
        AutoMigration(from = 1, to = 2),
        AutoMigration(from = 2, to = 3),
        AutoMigration(from = 3, to = 4),
    ],
)
abstract class LedgerDatabase : RoomDatabase() {
    abstract fun transactionDao(): TransactionDao
    abstract fun ruleDao(): RuleDao
    abstract fun senderDao(): SenderDao
    abstract fun categoryDao(): CategoryDao
    abstract fun ownAccountDao(): OwnAccountDao
    abstract fun ownAccountNameDao(): OwnAccountNameDao

    companion object {
        const val NAME = "ledger.db"

        /**
         * Splits categories into money-in and money-out sets.
         *
         * Hand-written rather than generated because adding the column is only
         * half the job: an existing ledger's categories all pre-date the split
         * and have to be assigned a side, and the new labels have to arrive
         * without disturbing the order or the names already in use.
         *
         * The one genuinely lossy decision is the old generic "Other". It served
         * both directions, and the split gives each side its own catch-all, so
         * spending filed there is relabelled to "Misc" and the freed name becomes
         * the income catch-all it now is. Restricting that relabel by `direction`
         * is what keeps it meaning-preserving: a debit filed under the general
         * catch-all is exactly a debit filed under the spending catch-all.
         *
         * Every statement is idempotent, and nothing is deleted.
         */
        val MIGRATION_4_5 = object : Migration(4, 5) {
            /** Categories from before the split that are unambiguously inflows.
             *  "Income" is no longer seeded, but a ledger upgraded from v2 has it
             *  and transactions filed under it. */
            private val LEGACY_INCOME = listOf("Income")

            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE categories ADD COLUMN kind TEXT NOT NULL DEFAULT 'OUT'")

                // Hand the spend side its own catch-all before "Other" changes
                // sides underneath it.
                val catchAll = DefaultCategories.SPEND_CATCH_ALL
                val legacy = DefaultCategories.INCOME_CATCH_ALL
                db.execSQL(
                    "UPDATE transactions SET category = ? WHERE category = ? AND direction = 'DEBIT'",
                    arrayOf(catchAll, legacy),
                )
                db.execSQL(
                    "UPDATE rules SET category = ? WHERE category = ? AND direction = 'DEBIT'",
                    arrayOf(catchAll, legacy),
                )

                // Assign sides. Anything the split doesn't name — including every
                // category the user made themselves — keeps the column default,
                // which is right: they were all created in a spend-only world.
                val income = DefaultCategories.ALL
                    .filter { it.kind == CategoryKind.IN }
                    .map { it.name } + LEGACY_INCOME
                db.execSQL(
                    "UPDATE categories SET kind = 'IN' WHERE name IN (${placeholders(income.size)})",
                    income.toTypedArray(),
                )
                db.execSQL(
                    "UPDATE categories SET kind = 'SHARED' WHERE name = ?",
                    arrayOf(DefaultCategories.TRANSFERS),
                )

                // Add whatever the new sets introduce, appended so the user's own
                // ordering survives. OR IGNORE leans on the unique name index.
                DefaultCategories.ALL.forEach { category ->
                    db.execSQL(
                        "INSERT OR IGNORE INTO categories (name, position, enabled, kind) " +
                            "SELECT ?, (SELECT COALESCE(MAX(position), -1) + 1 FROM categories), 1, ?",
                        arrayOf(category.name, category.kind.name),
                    )
                }
            }

            private fun placeholders(n: Int) = List(n) { "?" }.joinToString(",")
        }

        /**
         * Gives a wallet its own row instead of sharing one per phone number.
         *
         * One MSISDN commonly carries two wallets — an MTN MoMo and a GhanaPay
         * account on the same line — printing a different name each. With the
         * number as the primary key, adding the second silently replaced the
         * first and took its aliases with it, so only one could ever be
         * registered. Identity becomes (number, provider), which needs a new
         * primary key, so both tables are rebuilt.
         *
         * `institution` becomes NOT NULL DEFAULT '' because it now sits in a
         * unique index and SQLite treats NULLs as distinct — left nullable,
         * "not sure" could be added without limit.
         *
         * Nothing is dropped: existing rows keep their number, label, provider
         * and aliases, and simply gain an id.
         */
        val MIGRATION_5_6 = object : Migration(5, 6) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    "CREATE TABLE IF NOT EXISTS `own_accounts_new` (" +
                        "`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                        "`key` TEXT NOT NULL, `identifier` TEXT NOT NULL, `label` TEXT NOT NULL, " +
                        // No SQL DEFAULT: Room's TableInfo check compares defaults,
                        // and the entity declares none. The INSERT below supplies
                        // the value for every existing row instead.
                        "`addedAt` INTEGER NOT NULL, `institution` TEXT NOT NULL)"
                )
                db.execSQL(
                    "INSERT INTO `own_accounts_new` (`key`, `identifier`, `label`, `addedAt`, `institution`) " +
                        "SELECT `key`, `identifier`, `label`, `addedAt`, COALESCE(`institution`, '') FROM `own_accounts`"
                )
                db.execSQL("DROP TABLE `own_accounts`")
                db.execSQL("ALTER TABLE `own_accounts_new` RENAME TO `own_accounts`")
                db.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS `index_own_accounts_key_institution` " +
                        "ON `own_accounts` (`key`, `institution`)"
                )

                // Aliases move from pointing at the number to pointing at the row.
                // A name whose account somehow can't be resolved is dropped rather
                // than left dangling — it would match nothing and could never be
                // edited away from the UI.
                db.execSQL(
                    "CREATE TABLE IF NOT EXISTS `own_account_names_new` (" +
                        "`name` TEXT NOT NULL, `accountId` INTEGER NOT NULL, `display` TEXT NOT NULL, " +
                        "PRIMARY KEY(`name`))"
                )
                db.execSQL(
                    "INSERT INTO `own_account_names_new` (`name`, `accountId`, `display`) " +
                        "SELECT n.`name`, a.`id`, n.`display` FROM `own_account_names` n " +
                        "JOIN `own_accounts` a ON a.`key` = n.`accountKey`"
                )
                db.execSQL("DROP TABLE `own_account_names`")
                db.execSQL("ALTER TABLE `own_account_names_new` RENAME TO `own_account_names`")
                db.execSQL(
                    "CREATE INDEX IF NOT EXISTS `index_own_account_names_accountId` " +
                        "ON `own_account_names` (`accountId`)"
                )
            }
        }
    }
}
